name: Build and deploy Github pages

on:
  push:
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libusb-1.0-0-dev libudev-dev

      - name: Install Python dependencies
        run: |
          pip3 install setuptools
          pip3 install nox

      - name: Build Sphinx Doc
        run: |
          nox --session gendoc

      - name: Deploy Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/html
